function mat2DWInhdr(fn, nrrdStructure)

% fn = file name
% nrrdStrcuture = the structure containing all the info
  
  fid = fopen([fn '.nhdr'], 'w');
  fprintf(fid, ['NRRD0005\n' ...
                '# Complete NRRD file format specification at:\n' ...
                '# http://teem.sourceforge.net/nrrd/format.html\n' ...
                'type: float\n' ...
                'dimension: 4\n' ...
                'space: left-posterior-superior\n' ...
                'sizes: %d %d %d %d\n' ...
                'space directions: (1.6667,0,0) (0,1.6667,0) (0,0,-1.7) none\n' ...
                'centerings: cell cell cell ???\n',...
                'kinds: space space space list\n' ...
                'endian: little\n' ...
                'encoding: gzip\n' ...
                'space origin: (-119.169,-119.169,71.4)\n' ...
                'measurement frame: (-1,0,0) (0,-1,0) (0,0,1)\n',...
                'space units: "mm" "mm" "mm"\n',...
                'data file: %s.raw.gz\n'...
                'modality:=DWMRI\n' ...
                'DWMRI_b-value:=900\n'], ...
          size(nrrdStructure.data,1), size(nrrdStructure.data,2), size(nrrdStructure.data,3), size(nrrdStructure.data,4),fn);
      
  for j = 1:size(nrrdStructure.gradients,1)
    fprintf(fid,'DWMRI_gradient_%04d:= %f %f %f\n',j-1,nrrdStructure.gradients(j,1),nrrdStructure.gradients(j,2),nrrdStructure.gradients(j,3));
  end
  fclose(fid);
  
  
  fid = fopen([fn '.raw'], 'w');
  fwrite(fid, single(nrrdStructure.data), 'single');
  fclose(fid);
  system(['rm -f ' fn '.raw.gz && gzip ' fn '.raw']); % compress
  %saveNrrdStructure([fn '.nhdr'],nrrdStructure);
  
end
