function mat2nhdr(m, fn)
  fid = fopen([fn '.nhdr'], 'w');
  fprintf(fid, ['NRRD0004\n' ...
                '# Complete NRRD file format specification at:\n' ...
                '# http://teem.sourceforge.net/nrrd/format.html\n' ...
                'type: unsigned short\n' ...
                'dimension: 3\n' ...
                'space: left-posterior-superior\n' ...
                'sizes: %d %d %d\n' ...
                'space directions: (1.6667,0,0) (0,1.6667,0) (0,0,-1.7)\n' ...
                'kinds: domain domain domain\n' ...
                'endian: little\n' ...
                'encoding: gzip\n' ...
                'space origin: (-119.169,-119.169,71.4)\n' ...
                'data file: %s.raw.gz\n'], ...
          size(m), fn);

  fclose(fid);
  
  
  fid = fopen([fn '.raw'], 'w');
  fwrite(fid, uint16(m), 'uint16');
  fclose(fid);
  system(['rm -f ' fn '.raw.gz && gzip ' fn '.raw']); % compress
end
