function mat2nhdr_AG(m, fn)
  fid = fopen([fn '.nhdr'], 'w');
  fprintf(fid, ['NRRD0004\n' ...
                '# Complete NRRD file format specification at:\n' ...
                '# http://teem.sourceforge.net/nrrd/format.html\n' ...
                'type: float\n' ...
                'dimension: 3\n' ...
                'space: left-posterior-superior\n' ...
                'sizes: %d %d %d\n' ...
                'space directions: (-1,0,0) (0,-1,0) (0,0,3)\n' ...
                'kinds: domain domain domain\n' ...
                'endian: little\n' ...
                'encoding: gzip\n' ...
                'space origin: (127.5,127.5,-64.5)\n' ...
                'data file: %s.raw.gz\n'], ...
          size(m), fn);

  fclose(fid);
  
  
  fid = fopen([fn '.raw'], 'w');
  fwrite(fid, single(m), 'single');
  fclose(fid);
  system(['rm -f ' fn '.raw.gz && gzip ' fn '.raw']); % compress
end
